name: flutter_app
description: "Enterprise-grade EdTech application for 100k+ students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2
  fl_chart: ^0.70.2
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.5
  get_storage: ^2.1.1
  intl: ^0.19.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
