global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    dns_sd_configs:
      - names:
          - 'tasks.api-gateway'
        type: 'A'
        port: 8000

  - job_name: 'auth-service'
    dns_sd_configs:
      - names:
          - 'tasks.auth-service'
        type: 'A'
        port: 8000

  - job_name: 'user-service'
    dns_sd_configs:
      - names:
          - 'tasks.user-service'
        type: 'A'
        port: 8000

  - job_name: 'chat-service'
    dns_sd_configs:
      - names:
          - 'tasks.chat-service'
        type: 'A'
        port: 8000

  - job_name: 'rag-service'
    dns_sd_configs:
      - names:
          - 'tasks.rag-service'
        type: 'A'
        port: 8000

  - job_name: 'exam-service'
    dns_sd_configs:
      - names:
          - 'tasks.exam-service'
        type: 'A'
        port: 8000

  - job_name: 'notification-service'
    dns_sd_configs:
      - names:
          - 'tasks.notification-service'
        type: 'A'
        port: 8000
